### PR TITLE
Update to Temp fault sketches to match changes in tempmon.c

### PR DESCRIPTION
**Pull request by mjs513**
This is an update to the fault sketches fixing to match the changes in tempmon.c fixing the temp and error in setting alarm temps over 95.  Yes I know that it only makes sense for Panic alarm but still had to fix.

### CODE REVIEW

**Comment by mjs513** [comment]
Going to close it - found another bug....

**Comment by mjs513** [comment]
Figured out the issue I was having was my fat fingering with the sketch.  Hopefully...  But the tempmon.c is correct I tested independently of the test sketch by changing the alarm temps and see it it hit, it worked as expected

**Comment by PaulStoffregen** [comment]
should I merge this?

**Comment by mjs513** [comment]
Sorry Paul was off doing errands and chores just saw this.  Answer to your question is yes it can be merged but fair warning to work without errors above 95 the PR for tempmon.c needs to be incorporated:  https://github.com/PaulStoffregen/cores/pull/590

**Pull request merged**
